-- Add missing columns to products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS on_sale BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS backorders_allowed BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS backordered BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS shipping_required BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS shipping_taxable BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reviews_allowed BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS date_on_sale_from TIMESTAMP;
ALTER TABLE products ADD COLUMN IF NOT EXISTS date_on_sale_to TIMESTAMP;

-- Add missing columns to variations table
ALTER TABLE variations ADD COLUMN IF NOT EXISTS on_sale BOOLEAN DEFAULT FALSE;
ALTER TABLE variations ADD COLUMN IF NOT EXISTS woo_parent_id INTEGER;
